shops/urls.py
from django.urls import path
from shops import views

app_name = 'shops'

urlpatterns = [
    path('', views.shops, name='list'),
    path('create', views.shops_create, name='create'),
    path('update', views.shops_update, name='update'),
    path('delete/<int:pk>', views.shops_delete, name='delete'),
]

users_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users_app import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.index, name='index'),
    path('users/', users_views.users_list, name='users-list'),
    path('users/create', users_views.create_user, name='users-create'),
    path('users/update', users_views.update_user, name='users-update'),
    path('users/delete/<int:pk>', users_views.delete_user, name='users-delete'),
    path('login/', users_views.LogIn.as_view(), name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('loggedin/', users_views.logged_in_view, name='loggedin'),
    path('shops/', include('shops.urls'))
]

shops/models.py
from django.db import models
from django.conf import settings
from django.db.models.constraints import UniqueConstraint


class ShopModel(models.Model):

    shop_number = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=150)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        db_table = 'shops'
        constraints = [
            UniqueConstraint(fields=['name', 'user'], name='unique_shop')
        ]

users_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

shops/forms.py
from django import forms
from .models import ShopModel


class CreateShopForm(forms.ModelForm):

    class Meta:
        model = ShopModel
        fields = '__all__'


class UpdateShopForm(forms.ModelForm):
    """ For now Update and Create forms are the same. But we should follow single responsibility rule and
            keep them separate for future changes... """
    class Meta:
        model = ShopModel
        fields = ('user', 'name', 'shop_number')

users_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'is_staff', 'is_superuser')


class MyUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'is_staff', 'is_superuser')


class MyAuthenticationForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

shops/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test

from .models import ShopModel
from .forms import UpdateShopForm, CreateShopForm


@user_passes_test(lambda u: u.is_superuser)
def shops(request):
    return render(request, 'shops/shops.html', context={
        'shops': ShopModel.objects.all(),
        'update_shop_form': UpdateShopForm(),
        'create_shop_form': CreateShopForm()
    })


def shops_create(request):
    create_form = CreateShopForm(request.POST)
    if create_form.is_valid():
        create_form.save()
        return redirect('shops:list')
    return render(request, 'shops/shops.html', context={
        'shops': ShopModel.objects.all(),
        'update_shop_form': UpdateShopForm(),
        'create_shop_form': create_form
    })


def shops_update(request):
    shop = get_object_or_404(ShopModel, pk=request.POST.get('shop_number'))
    update_form = UpdateShopForm(request.POST, instance=shop)
    if update_form.is_valid():
        update_form.save()
        return redirect('shops:list')
    return render(request, 'shops/shops.html', context={
        'shops': ShopModel.objects.all(),
        'update_shop_form': update_form,
        'create_shop_form': CreateShopForm()
    })


def shops_delete(request, pk):
    shop = get_object_or_404(ShopModel, pk=pk)
    shop.delete()
    return redirect('shops:list')

users_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, authenticate, logout, login
from django.views.generic import View
from django.contrib.auth.mixins import UserPassesTestMixin

from .forms import MyAuthenticationForm, MyUserChangeForm, MyUserCreationForm


def index(request):
    return render(request, 'index.html')


def users_list(request):
    return render(request, 'users_app/users.html', context={
        'users': get_user_model().objects.all(),
        'user_create_form': MyUserCreationForm(),
        'user_update_form': MyUserChangeForm()
    })


def create_user(request):
    create_user_form = MyUserCreationForm(request.POST)
    if create_user_form.is_valid():
        create_user_form.save()
        return redirect('users-list')
    return render(request, 'users_app/users.html', context={
        'users': get_user_model().objects.all(),
        'user_create_form': create_user_form,
        'user_update_form': MyUserChangeForm()
    })


def update_user(request):
    """ As we want to update any User from this view, we should get each user dynamic """
    user_obj = get_user_model().objects.get(username=request.POST.get('username'))
    update_user_form = MyUserChangeForm(request.POST, instance=user_obj)
    if update_user_form.is_valid():
        update_user_form.save()
        return redirect('users-list')
    return render(request, 'users_app/users.html', context={
        'users': get_user_model().objects.all(),
        'user_create_form': MyUserCreationForm(),
        'user_update_form': update_user_form
    })


def delete_user(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    user.delete()
    return redirect('users-list')


class LogIn(UserPassesTestMixin, View):

    def test_func(self):
        return not self.request.user.is_authenticated

    def get(self, request):
        auth_form = MyAuthenticationForm()
        return render(request, 'users_app/login.html', context={'auth_form': auth_form})

    def post(self, request):
        auth_form = MyAuthenticationForm(data=request.POST)
        if auth_form.is_valid():
            username = auth_form.cleaned_data['username']
            password = auth_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('loggedin')
            return render(request, 'users_app/login.html', context={'auth_form': auth_form})
        return render(request, 'users_app/login.html', context={'auth_form': auth_form})


def logout_view(request):
    logout(request)
    return redirect('login')


def logged_in_view(request):
    return render(request, 'users_app/loggedin.html')

shops/templates/shops/shops.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
    Shops
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'shops/shops.css' %}">
{% endblock %}

{% block content %}
    <section class="section container">
        {% for shop in shops %}
            <div class="row">
                <div class="col shop__item bg-info">
                    <div class="container">
                        <div class="row">
                            <div class="col text-center">{{ shop.shop_number }}</div>
                            <div class="col text-center">{{ shop.name }}</div>
                            <div class="col text-center">{{ shop.user.username }}</div>
                        </div>
                    </div>
                    <a class="btn btn-block btn-danger" href="{% url 'shops:delete' pk=shop.pk %}">Delete Shop</a>
                </div>
            </div>
        {% empty %}
            <div class="row">
                <div class="col">
                    There are no shops...
                </div>
            </div>
        {% endfor %}
    </section>
    <section class="section container create-shop">
        <h1 class="text-center">Create shop below:</h1>
        <form action="{% url 'shops:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form create_shop_form layout="horizontal" %}
            <button class="btn btn-block btn-success" type="submit">Create Shop</button>
        </form>
    </section>
    <section class="section container update-shop">
        <h1 class="text-center">Update shop item below:</h1>
        <form action="{% url 'shops:update' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form update_shop_form layout="horizontal" %}
            <button class="btn btn-block btn-success" type="submit">Update Shop</button>
        </form>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block stylesheet %}{% endblock %}
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1 class="text-center">C U Soon :) </h1>
            <a class="btn btn-block btn-warning" href="{% url 'logout' %}">Logout</a>
            {% if user.is_superuser %}
                    <a class="btn btn-block btn-warning" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
        {% else %}
            <h1 class="text-center">This is home page! All magic happens when you log in...</h1>
            <a class="btn btn-block btn-success" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
{% endblock %}

users_app/templates/users_app/loggedin.html
{% extends 'base.html' %}

{% block title %}
    Welcome!
{% endblock title %}


{% block content %}
    <div class="jumbotron">
        <h1 class="text-center">Hello, {{request.user.username}} !</h1>
        <a class="btn btn-block btn-danger" href="{% url 'logout' %}">Logout</a>
        {% if request.user.is_superuser %}
        <h2 class="text-center">As you're superuser, you can check out some more stuff!</h2>
            <a class="btn btn-block btn-info" href="{% url 'users-list' %}">Users</a>
            <a class="btn btn-block btn-warning" href="{% url 'shops:list' %}">Shops</a>
        {% endif %}
    </div>
{% endblock content %}

users_app/templates/users_app/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1 class="text-center">Please, fill in your credentials</h1>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form auth_form layout="horizontal" %}
        <button class="btn btn-block btn-success">Login</button>
    </form>
</div>
{% endblock content %}

users_app/templates/users_app/users.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block title %}
    Users
{% endblock title %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'users_app/users.css' %}">
{% endblock stylesheet %}

{% block content %}
<div class="jumbotron text-center">
  <h1 class="text-center">Hello{% if request.user.is_authenticated %}, {{request.user.username}}{% endif %}!</h1>
  <h2>Currently registered users:</h2>
  <section class="section users container-fluid">
    <div class="container">
    </div>
    {% for user in users %}
      <div class="row m-2">
        <div class="col">
          <div class="user__item bg-info">
            {{ user.username }}
              <a class="btn btn-block btn-danger" href="{% url 'users-delete' pk=user.pk %}">Delete user - {{ user.username }}</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </section>
  <section class="section users__create container-fluid">
    <h2 class="text-center">Create new user:</h2>
    <form action="{% url 'users-create' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form user_create_form layout='horizontal' %}
      <button class="btn btn-block btn-success" type="submit">Create new user</button>
    </form>
  </section>
  <section class="section users__update container-fluid">
    <h2 class="text-center">Update existing user:</h2>
    <form action="{% url 'users-update' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form user_update_form layout='horizontal' %}
      <button class="btn btn-block btn-success" type="submit">Update user</button>
    </form>
  </section>
</div>

{% endblock content %}